# *****************************************************
# *****************************************************
# Dictionary.py
# Version: 1.2
# Date: 5/31/2024
# Last Modified Date: 9/22/2025
# Original Author: Matthew Bell, Michigan Geological Survey, matthew.e.bell@wmich.edu
# Description: A Python script that outlines all the definitions for domains that are used in the various geodatabases.
# *****************************************************
# *****************************************************
import Utility_Functions as uf
version = "Dictonary.py, Version 1.2.5"
url = "https://raw.githubusercontent.com/MichiganGeologicalSurvey/Michigan-Geological-Survey-Cross-Section-Tool/refs/heads/Master/Scripts/Dictonary.py"
uf.management.githubVersion(
    vString=version,
    rawurl=url
)
colors =  {
    "Black": "Black",
    "Black & Gray": "Black & Gray",
    "Blue": "Blue",
    "Brown": "Brown",
    "Cream": "Cream",
    "Gray": "Gray",
    "Green": "Green",
    "Orange": "Orange",
    "Pink": "Pink",
    "Red": "Red",
    "Rust": "Rust",
    "Tan": "Tan",
    "White": "White",
    "Black & White": "Black & White",
    "Dark Gray": "Dark Gray",
    "Gray & White": "Gray & White",
    "LIGHT BROWN": "Light Brown",
    "Light Gray": "Light Gray",
    "Tan & Gray": "Tan & Gray",
    "Yellow": "Yellow"
}
consistency = {
    "Dense": "Dense",
    "Dry": "Dry",
    "Gummy": "Gummy",
    "Karst": "Karst",
    "Porous": "Porous",
    "Strips": "Strips",
    "Cemented": "Cemented",
    "Very Hard": "Very Hard",
    "Broken": "Broken",
    "Fractured": "Fractured",
    "Heaving/Quick": "Heaving/Quick",
    "Stringers": "Stringers",
    "Swelling": "Swelling",
    "Water Bearing": "Water Bearing",
    "Weathered": "Weathered",
    "Wet/Moist": "Wet/Moist",
    "Firm": "Firm",
    "Hard": "Hard",
    "Soft": "Soft"
}
formationNames = {
    "AGR": "Archean Granite & Gneissic",
    "ANT": "Antrim Shale",
    "AUM": "Archean Ultramafic",
    "AVS": "Archean Volcanic & Sedimentary",
    "BAY": "Bayport Limestone",
    "BBF": "Bois Blanc Formation",
    "BBG": "Burnt Bluff Group",
    "BDG": "Badwater Greenstone",
    "BED": "Bedford Shale",
    "BER": "Berea Sandstone & Bedford Shale",
    "BHD": "Big Hill Dolomite",
    "BIF": "Bijiki Iron Formation",
    "BIG": "Bass Island Group",
    "BLS": "Bell Shale",
    "BRG": "Black River Group",
    "CHC": "Copper Harbor Conglomerate",
    "CHO": "Chocolay Group",
    "CHS": "Cabot Head Shale",
    "CSM": "Collingwood Shale Member",
    "CWT": "Coldwater Shale",
    "DCF": "Dunn Creek Formation",
    "DDL": "Dundee Limestone",
    "DRG": "Detroit River Group",
    "ELL": "Ellsworth Shale",
    "ENG": "Engadine Group",
    "EVC": "Emperor Volcanic Complex",
    "FSS": "Freda Sandstone",
    "GDQ": "Goodrich Quartzite",
    "GIF": "Garden Island Formation",
    "GLA": "Glacial Drift",
    "GRF": "Grand River Formation",
    "HEM": "Hemlock Formation",
    "IIF": "Ironwood Iron Formation",
    "INT": "Intrusive",
    "JAC": "Jacobsville Sandstone",
    "MAC": "Mackinac Breccia",
    "MAR": "Marshall Formation",
    "MCG": "Menominee & Chocolay Groups",
    "MGF": "Michigamme Formation",
    "MIF": "Michigan Formation",
    "MND": "Manitoulin Dolomite",
    "MQG": "Manistique Group",
    "MUN": "Munising Formation",
    "NIF": "Negaunee Iron Formation",
    "NSF": "Nonesuch Formation",
    "OBF": "Oak Bluff Formation",
    "PAC": "Point Aux Chenes Shale",
    "PAF": "Palms Formation",
    "PDC": "Prairie Du Chien Group",
    "PLV": "Portage Lake Volcanics",
    "PRG": "Paint River Group",
    "QUF": "Quinnesec Formation",
    "QUS": "Queenston Shale",
    "RAD": "Randville Dolomite",
    "RBD": "Jurassic Red Beds",
    "RIF": "Riverton Iron Formation",
    "SAG": "Saginaw Formation",
    "SAL": "Salina Group",
    "SAQ": "Siamo Slate & Ajibik Quartzite",
    "SCF": "Siemens Creek Formation",
    "SID": "Saint Ignace Dolomite",
    "SSS": "Sylvania Sandstone",
    "STF": "Stonington Formation",
    "SUN": "Sunbury Shale",
    "TMP": "Trempealeau Formation",
    "TRG": "Traverse Group",
    "TRN": "Trenton Group",
    "USM": "Utica Shale Member",
    "PSS": "Parma Sandstone",
    "GRG": "Grand Rapids Group",
    "NSS": "Napolean Sandstone",
    "SBL": "Squaw Bay Limestone",
    "ALL": "Alpena Limestone",
    "AMF": "Amherstburg Formation",
    "LUF": "Lucas Formation",
    "RCL": "Rogers City Limestone",
    "NIA": "Niagara Group",
    "CAG": "Cataract Group",
    "RIG": "Richmond Group",
    "GLM": "Glenwood Member",
    "JSS": "Jordan Sandstone",
    "SPS": "Saint Peter Sandstone",
    "LOD": "Lodi Member",
    "NRS": "New Richard Sandstone",
    "OND": "Oneota Dolomite",
    "SHD": "Shakopee Dolomite",
    "SLM": "Saint Lawrence Member",
    "DSS": "Dresbach Sandstone",
    "ECM": "Eau Claire Member",
    "FRS": "Franconia Sandstone",
    "LSG": "Lake Superior Group",
    "MSS": "Mount Simon Sandstone",
    "PRE": "Precambrian Bedrock (Undefined)",
    "UNK": "Unknown Group",
    "AMA": "Amasa Formation"
}
qGeology = {
    "W":"Water",
    "02":"Peat & Muck",
    "03":"Postglacial Alluvium",
    "04":"Dune Sand",
    "05":"Lacustrine (Clay & Silt)",
    "06":"Lacustrine (Sand & Gravel)",
    "07":"Glacial Outwash Sand and Gravel & Postglacial Alluvium",
    "08":"Ice-Contact Outwash Sand and Gravel",
    "09":"Glacial Till (Fine-Grained)",
    "10":"End Moraine (Fine-Textured Till)",
    "11":"Glacial Till (Medium-Grained)",
    "12":"End Moraine (Medium-Textured Till)",
    "13":"Glacial Till (Coarse-Grained)",
    "14":"End Moraine (Coarse-Textured Till)",
    "15":"Thin to Discontinuous Glacial Till over Bedrock",
    "16":"Artificial Fill",
    "17":"Exposed Bedrock"
}
aggDict = {
    "UNK": "Unknown or No Record",
    "BDRK": "Bedrock",
    "CLAY": "Clay",
    "CLSA": "Clay & Sand",
    "DIAM": "Diamicton",
    "TOPS": "Topsoil",
    "GRAV": "Gravel",
    "FSAN": "Fine Sand",
    "ORGA": "Organics",
    "SAND": "Sand",
    "SAGR": "Sand & Gravel"
}
lithAquifer = {
    "D-AQ": "Drift: Aquifer Material",
    "D-MAQ": "Drift: Marginal Aquifer Material",
    "D-CM": "Drift: Confining Material",
    "D-PCM": "Drift: Partially Confining Material",
    "R-AQ": "Bedrock: Aquifer Material",
    "R-MAQ": "Bedrock: Marginal Aquifer Material",
    "R-CM": "Bedrock: Confining Material",
    "R-PCM": "Bedrock: Partially Confining Material",
    "D-NA": "Drift: Unknown Material",
    "R-NA": "Bedrock: Unknown Material",
    "U-NA": "Unknown: Unknown Material"
}
primLithology = {
    "Basalt": "Basalt",
    "Boulders": "Boulders",
    "Clay": "Clay",
    "Clay & Boulders": "Clay & Boulders",
    "Clay & Cobbles": "Clay & Cobbles",
    "Clay & Gravel": "Clay & Gravel",
    "Clay & Sand": "Clay & Sand",
    "Clay & Silt": "Clay & Silt",
    "Clay & Stones": "Clay & Stones",
    "Clay Gravel Sand": "Clay Gravel Sand",
    "Clay Gravel Silt": "Clay Gravel Silt",
    "Clay Gravel Stones": "Clay Gravel Stones",
    "Clay Sand Gravel": "Clay Sand Gravel",
    "Clay Sand Silt": "Clay Sand Silt",
    "Clay Silt Gravel": "Clay Silt Gravel",
    "Clay Silt Sand": "Clay Silt Sand",
    "Coal": "Coal",
    "Cobbles": "Cobbles",
    "Conglomerate": "Conglomerate",
    "Debris": "Debris",
    "Dolomite": "Dolomite",
    "Dolomite & Limestone": "Dolomite & Limestone",
    "Dolomite & Sandstone": "Dolomite & Sandstone",
    "Dolomite & Shale": "Dolomite & Shale",
    "Dry Hole": "Dry Hole",
    "Granite": "Granite",
    "Gravel": "Gravel",
    "Gravel & Boulders": "Gravel & Boulders",
    "Gravel & Clay": "Gravel & Clay",
    "Gravel & Cobbles": "Gravel & Cobbles",
    "Gravel & Sand": "Gravel & Sand",
    "Gravel & Silt": "Gravel & Silt",
    "Gravel & Stones": "Gravel & Stones",
    "Gravel Clay Sand": "Gravel Clay Sand",
    "Gravel Clay Silt": "Gravel Clay Silt",
    "Gravel Sand Clay": "Gravel Sand Clay",
    "Gravel Sand Silt": "Gravel Sand Silt",
    "Gravel Silt Clay": "Gravel Silt Clay",
    "Gravel Silt Sand": "Gravel Silt Sand",
    "Greenstone": "Greenstone",
    "Gypsum": "Gypsum",
    "Hardpan": "Hardpan",
    "Interval Not Sampled": "Interval Not Sampled",
    "Iron Formation": "Iron Formation",
    "Limestone": "Limestone",
    "Limestone & Dolomite": "Limestone & Dolomite",
    "Limestone & Sandstone": "Limestone & Sandstone",
    "Limestone & Shale": "Limestone & Shale",
    "Lithology Unknown": "Lithology Unknown",
    "Loam": "Loam",
    "Marl": "Marl",
    "Muck": "Muck",
    "Mud": "Mud",
    "No Lithology Information": "No Lithology Information",
    "No Log": "No Log",
    "Peat": "Peat",
    "Quartz": "Quartz",
    "Quartzite": "Quartzite",
    "Sand": "Sand",
    "Sand & Boulders": "Sand & Boulders",
    "Sand & Clay": "Sand & Clay",
    "Sand & Cobbles": "Sand & Cobbles",
    "Sand & Gravel": "Sand & Gravel",
    "Sand & Silt": "Sand & Silt",
    "Sand & Stones": "Sand & Stones",
    "Sand Clay Gravel": "Sand Clay Gravel",
    "Sand Clay Silt": "Sand Clay Silt",
    "Sand Gravel Clay": "Sand Gravel Clay",
    "Sand Gravel Silt": "Sand Gravel Silt",
    "Sand Silt Clay": "Sand Silt Clay",
    "Sand Silt Gravel": "Sand Silt Gravel",
    "Sandstone": "Sandstone",
    "Sandstone & Limestone": "Sandstone & Limestone",
    "Sandstone & Shale": "Sandstone & Shale",
    "Schist": "Schist",
    "See Comments": "See Comments",
    "Shale": "Shale",
    "Shale & Coal": "Shale & Coal",
    "Shale & Limestone": "Shale & Limestone",
    "Shale & Sandstone": "Shale & Sandstone",
    "Shale Sandstone Limestone": "Shale Sandstone Limestone",
    "Silt": "Silt",
    "Silt & Boulders": "Silt & Boulders",
    "Silt & Clay": "Silt & Clay",
    "Silt & Cobbles": "Silt & Cobbles",
    "Silt & Gravel": "Silt & Gravel",
    "Silt & Sand": "Silt & Sand",
    "Silt & Stones": "Silt & Stones",
    "Silt Clay Gravel": "Silt Clay Gravel",
    "Silt Clay Sand": "Silt Clay Sand",
    "Silt Gravel Clay": "Silt Gravel Clay",
    "Silt Gravel Sand": "Silt Gravel Sand",
    "Silt Sand Clay": "Silt Sand Clay",
    "Silt Sand Gravel": "Silt Sand Gravel",
    "Slate": "Slate",
    "Soapstone (Talc)": "Soapstone (Talc)",
    "Stones": "Stones",
    "Topsoil": "Topsoil",
    "Unidentified Consolidated Fm": "Unidentified Consolidated Fm",
    "Unknown": "Unknown",
    "Void": "Void"
}
lithModifer = {
    "Clayey": "Clayey",
    "Dolomitic": "Dolomitic",
    "Fill": "Fill",
    "Gravely": "Gravely",
    "Organic": "Organic",
    "Sandy": "Sandy",
    "Silty": "Silty",
    "Stoney": "Stoney",
    "W/Boulders": "With Boulders",
    "W/Clay": "With Clay",
    "W/Coal": "With Coal",
    "W/Cobbles": "With Cobbles",
    "W/Dolomite": "With Dolomite",
    "W/Gravel": "With Gravel",
    "W/Gypsum": "With Gypsum",
    "W/Limestone": "With Limestone",
    "W/Pyrite": "With Pyrite",
    "W/Sand": "With Sand",
    "W/Sandstone": "With Sandstone",
    "W/Shale": "With Shale",
    "W/Silt": "With Silt",
    "W/Stones": "With Stones",
    "Wood": "Wood"
}
lithSimplified = {
    "UNK": "Unknown Sediment Type",
    "FINE": "Fine-Grained Sediments",
    "COARSE": "Coarse-Grained Sediments",
    "MIXED": "Mixed-Grained Sediments",
    "ORGANIC": "Organic Sediments",
    "BEDROCK": "Bedrock Unit"
}
texture = {
    "Coarse": "Coarse",
    "Fine": "Fine",
    "Medium": "Medium",
    "Fine To Coarse": "Fine To Coarse",
    "Fine To Medium": "Fine To Medium",
    "Medium To Coarse": "Medium To Coarse",
    "Very Coarse": "Very Coarse",
    "Very Fine": "Very Fine",
    "Very Fine-Coarse": "Very Fine To Coarse",
    "Very Fine-Fine": "Very Fine to Fine",
    "Very Fine-Medium": "Very Fine To Medium"
}
drillDict = {
    "OTH": "Other",
    "AUGBOR": "Auger/Bored",
    "CABTOO": "Cable Tool",
    "CASHAM": "Casing Hammer",
    "DRIVEN": "Driven Hand",
    "HOLROD": "Hollow Rod",
    "JETTIN": "Jetted",
    "TOOHAM": "Cable Tool w/Casing Hammer",
    "ROTARY": "Mud Rotary",
    "ROTHAM": "Rotary w/Casing Hammer",
    "UNK": "Unknown"
}
wellStatus = {
    "OTH": "Other",
    "ACT": "Active",
    "INACT": "Inactive",
    "PLU": "Plugged/Abandoned",
    "UNK": "Unknown"
}
testMeth = {
    "UNK": "Unknown",
    "OTH": "Other",
    "AIR": "Air",
    "BAIL": "Bailer",
    "PLUGR": "Plunger",
    "TSTPUM": "Test Pump"
}
verification = {
    "Y": "Yes",
    "N": "No",
    "U": "Unknown",
    "NA": "Not Applicable"
}
wellAquifer = {
    "DRIFT": "Drift Aquifer",
    "ROCK": "Bedrock Aquifer",
    "UNK": "Unknown Aquifer",
    "DRYHOL": "Dry Hole"
}
wellTypes = {
    "OTH": "Other",
    "HEATP": "Heat Pump",
    "HOSHLD": "Household",
    "INDUS": "Industrial",
    "IRRI": "Irrigation",
    "TESTW": "Test Well",
    "TY1PU": "Type I Public Supply",
    "TY2PU": "Type II Public Supply",
    "TY3PU": "Type III Public Supply",
    "HEATRE": "Heat Pump: Return",
    "HEATSU": "Heat Pump: Supply"
}
caseDict = {
    "OTH": "Other",
    "UNK": "Unknown",
    "PVCPLA": "PVC Plastic",
    "STEBLA": "Steel: Black",
    "STEGAL": "Steel: Galvanized",
    "STEUNK": "Steel: Unknown",
    "NONE": "No Casing"
}
directions = {
    "E-W": "East - West",
    "W-E": "West - East",
    "N-S": "North - South",
    "S-N": "South - North",
    "NW-SE": "Northwest - Southeast",
    "SE-NW": "Southeast - Northwest",
    "NE-SW": "Northeast - Southwest",
    "SW-NE": "Southwest - Northeast"
}
roadCodes = {
    "0":"Non-Certified",
    "1":"Interstate",
    "2":"Other Freeway",
    "3":"Other Principal Arterial",
    "4":"Minor Arterial",
    "5":"Major Collector",
    "6":"Minor Collector",
    "7":"NFC Local"
}
stateAbbr = {
    "Alabama":"AL",
    "Alaska":"AK",
    "Arizona":"AZ",
    "Arkansas":"AR",
    "California":"CA",
    "Colorado":"CO",
    "Connecticut":"CT",
    "Delaware":"DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illionis": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY"
}
wellId_county = {
    "Alcona":"01",
    "Alger":"02",
    "Allegan":"03",
    "Alpena":"04",
    "Antrim":"05",
    "Arenac":"06",
    "Baraga":"07",
    "Barry":"08",
    "Bay":"09",
    "Benzie":"10",
    "Berrien":"11",
    "Branch":"12",
    "Calhoun":"13",
    "Cass":"14",
    "Charlevoix":"15",
    "Cheboygan":"16",
    "Chippewa":"17",
    "Clare":"18",
    "Clinton":"19",
    "Crawford":"20",
    "Delta":"21",
    "Dickinson":"22",
    "Eaton":"23",
    "Emmet":"24",
    "Genesee":"25",
    "Gladwin":"26",
    "Gogebic":"27",
    "Grand Traverse":"28",
    "Gratiot":"29",
    "Hillsdale":"30",
    "Houghton":"31",
    "Huron":"32",
    "Ingham":"33",
    "Ionia":"34",
    "Iosco":"35",
    "Iron":"36",
    "Isabella":"37",
    "Jackson":"38",
    "Kalamazoo":"39",
    "Kalkaska":"40",
    "Kent":"41",
    "Keweenaw":"42",
    "Lake":"43",
    "Lapeer":"44",
    "Leelanau":"45",
    "Lenawee":"46",
    "Livingston":"47",
    "Luce":"48",
    "Mackinac":"49",
    "Macomb":"50",
    "Manistee":"51",
    "Marquette":"52",
    "Mason":"53",
    "Mecosta":"54",
    "Menominee":"55",
    "Midland":"56",
    "Missaukee":"57",
    "Monroe":"58",
    "Montcalm":"59",
    "Montmorency":"60",
    "Muskegon":"61",
    "Newaygo":"62",
    "Oakland":"63",
    "Oceana":"64",
    "Ogemaw":"65",
    "Ontonagon":"66",
    "Osceola":"67",
    "Oscoda":"68",
    "Otsego":"69",
    "Ottawa":"70",
    "Presque Isle":"71",
    "Roscommon":"72",
    "Saginaw":"73",
    "St. Clair":"74",
    "St. Joseph":"75",
    "Sanilac":"76",
    "Schoolcraft":"77",
    "Shiawassee":"78",
    "Tuscola":"79",
    "Van Buren":"80",
    "Washtenaw":"81",
    "Wayne":"82",
    "Wexford":"83",
}
ssurgo_county = {
    "Alcona":"001",
    "Alger":"003",
    "Allegan":"005",
    "Alpena":"007",
    "Antrim":"009",
    "Arenac":"011",
    "Baraga":"013",
    "Barry":"015",
    "Bay":"017",
    "Benzie":"614",
    "Berrien":"021",
    "Branch":"023",
    "Calhoun":"025",
    "Cass":"027",
    "Charlevoix":"029",
    "Cheboygan":"031",
    "Chippewa":"033",
    "Clare":"035",
    "Clinton":"037",
    "Crawford":"039",
    "Delta":"041",
    "Dickinson":"043",
    "Eaton":"045",
    "Emmet":"047",
    "Genesee":"049",
    "Gladwin":"051",
    "Gogebic":"053",
    "Grand Traverse":"055",
    "Gratiot":"057",
    "Hillsdale":"059",
    "Houghton":"061",
    "Huron":"063",
    "Ingham":"065",
    "Ionia":"067",
    "Iosco":"069",
    "Iron":"071",
    "Isabella":"073",
    "Jackson":"075",
    "Kalamazoo":"077",
    "Kalkaska":"079",
    "Kent":"081",
    "Keweenaw":"605",
    "Isle Royale National Park":"606",
    "Lake":"600",
    "Lapeer":"087",
    "Leelanau":"089",
    "Lenawee":"091",
    "Livingston":"093",
    "Luce":"095",
    "Mackinac":"097",
    "Macomb":"099",
    "Manistee":"614",
    "Marquette":"103",
    "Mason":"105",
    "Mecosta":"107",
    "Menominee":"109",
    "Midland":"111",
    "Missaukee":"113",
    "Monroe":"115",
    "Montcalm":"117",
    "Montmorency":"119",
    "Muskegon":"121",
    "Newaygo":"123",
    "Oakland":"125",
    "Oceana":"127",
    "Ogemaw":"129",
    "Ontonagon":"131",
    "Osceola":"133",
    "Oscoda":"135",
    "Otsego":"137",
    "Ottawa":"139",
    "Presque Isle":"141",
    "Roscommon":"143",
    "Saginaw":"145",
    "St. Clair":"147",
    "St. Joseph":"149",
    "Sanilac":"151",
    "Schoolcraft":"153",
    "Shiawassee":"155",
    "Tuscola":"157",
    "Van Buren":"159",
    "Washtenaw":"161",
    "Wayne":"163",
    "Wexford":"600",
}
loc_methods = {
    "001":"Address Matching - House Number",
    "002":"Address Matching - Street Centerline",
    "004":"Address Matching - Nearest Intersection",
    "012":"GPS Carrier Phase Static Relative Position Tech",
    "013":"GPS Carrier Phase Kinematic Relative Position Tech",
    "014":"GPS Code Measurement Differential (DGPS)",
    "015":"GPS Precise Positioning Service",
    "016":"GPS Code Meas. Std. Positioning Service SA Off",
    "017":"GPS Std. Positioning Service SA On",
    "018":"Interpolation - Map",
    "019":"Interpolation - Aerial Photo",
    "020":"Interpolation - Satellite Photo",
    "025":"Classical Surveying Techniques",
    "027":"Section Centroid",
    "028":"Town/Range Centroid",
    "036":"Quarter-Quarter-Quarter Centroid",
    "OTH":"Other",
    "UNK":"Unknown"
}
elev_methods = {
    "003":"GPS Code Measurement Differential (DGPS)",
    "005":"GPS Code Meas. Std. Positioning Svc. SA Off",
    "007":"Classical Surveying Techniques",
    "014":"Topographic Map Interpolation",
    "OTH":"Other",
    "UNK":"Unknown"
}
reclassAQ = {
    "N":"No Lithology Record",
    "B":"Blank Noted Among the Strata",
    "D":"Drift (Glacial) Well",
    "R":"Bedrock Well",
    "U":"Unknown Lithology Noted Among the Strata"
}
flagDepth = {
    "0":"No Depth Issues",
    "1":"Well Depth = 0",
    "2":"Well Depth is shallower than 25 feet or deeper than 1000 feet"
}
flagElev = {
    "0":"No Elevation Issues",
    "1":"Elevation = 0",
    "2":"Elevation < 507 feet or elevation > 1980 feet",
    "3":"Elevation < the DEM minimum or elevation > DEM maximum",
    "4":"Elevation difference between Wellogic and DEM > 20 ft"
}
flagSWL = {
    "0":"No SWL Issues",
    "1":"SWL = 0",
    "2":"SWL >= to final depth in a bedrock well; SWL >= to bottom of screen in glacial well",
    "3":"SWL > 900 feet"
}
flagAQ = {
    "0":"No AQ Issues",
    "1":"Unknown lithologies",
    "2":"Depth Condition: Well depth is less than or equal to top of rock",
    "3":"Lithology Problem: A glacial unit was found below bedrock unit",
    "4":"Final Lithology: Bottom unit is bedrock and bottom of screen > 0 and bottom of screen <= to final depth"
}
flagScreen = {
    "0":"No Screen Issues",
    "1":"Top of screen < 1 foot or Bottom of screen < than 1 foot",
    "2":"Bottom of screen <= to the final depth and the final lithology is partially confining or confining material",
    "3":"Top of screen >= to the final depth"
}
wellFlags = {
    "D0":"Well lithology sequence has a record where depth is 0",
    "DL0":"Well lithology has a record where depth is less than 0",
    "DD":"Well lithology sequence has a record where the depth is duplicated",
    "T0":"Well lithology sequence has a record where the thickness is 0",
    "TL0":"Well lithology sequence has a record where the thickness is less then 0",
    "NL":"The well has no lithology records",
    "DST":"Max depth of the lithology sequences does not equal the sum of the thicknesses",
    "UL":"Well has one ore more lithology records where the hydraulic conductivity is 999999",
    "NSW":"No static water level recorded",
    "WBL":"Bottom of aquifer is below the max lithology depth",
    "TBB":"Top of aquifer is equal to or greater than the bottom of aquifer",
    "NLS":"No land system value",
    "AQ1":"Derived aquifer thickness is less than one foot and treated as 0",
    "RWD":"Drift sequences intersperse the rock lithology, top of rock set to max depth of drift."
}
landsystems = {
    "ICE-CONTACT OUTWASH":"Ice-Contact Outwash",
    "PROGLACIAL OUTWASH":"Proglacial Outwash",
    "LACUSTRINE - FINE":"Lacustrine - Fine",
    "LACUSTRINE - COARSE":"Lacustrine - Coarse",
    "LODGEMENT TILL OR FINE SUPRAGLACIAL DRIFT":"Lodgement Till or Fine Supraglacial Drift",
    "ICE-MARGINAL TILL":"Ice-Marginal Till",
    "COASTAL DUNES":"Coastal Dunes",
    "THIN DRIFT OVER BEDROCK":"Thin Drift over Bedrock",
    "BEDROCK":"Bedrock",
    "LAKE":"Lake"
}
screenType = {
    "R_US":"Bedrock Well: Open Hole",
    "R_S":"Bedrock Well: Screened",
    "D_US":"Drift Well: Open Hole",
    "D_S":"Drift Well: Screened",
    "U_US":"Unknown Well: Open Hole",
    "U_S":"Unknown Well: Screened"
}
aqUnits = {
    "UN":"Unconfined Aquifer",
    "CO":"Confined Aquifer",
    "SC":"Semiconfined Aquifer",
    "NA":"Not an Aquifer"
}